version: "3.7"

services:

  frontend:
    image: micadoproject/quasar:1.1.2-cypress
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: frontend
        target: /code
    ports:
      - "8000:8000"
      - "8080:8080"
    command: /bin/sh -c "npm install && quasar dev"
    networks:
      - refact_net

  balancer:
    image: traefik:v2.1
    ports:
      - "80:80"
      - "8081:8080"
      - "443:443" # The HTTPS port
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/dynamic.toml:/etc/traefik/dynamic.toml
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/certs:/etc/certs # SSL Development certificates
    networks:
      - refact_net
  micado_db:
    image: mdillon/postgis:11-alpine
    env_file:
      - .env
      - prod.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
      - type: volume
        source: postgres_init
        target: /docker-entrypoint-initdb.d
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - refact_net
  backend:
    image: micadoproject/micado_backend_rfc
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: backend
        target: /code
    ports:
      - "3000:3000"
    #     - "8080:8080"
    #    command: /bin/sh -c "cd backend && npm start"
    command: /bin/sh -c "bash"
    env_file:
      - .env
      - prod.env
    environment:
      - ALGORITHM_PASSWORD=${ALGORITHM_PASSWORD}
      - MICADO_DB_PWD=${MICADO_DB_PWD}
      - MICADO_DB_USER=${MICADO_DB_USER}
      - MICADO_DB_SCHEMA=${MICADO_DB_SCHEMA}
    networks:
      - refact_net
  keycloak:
    image: jboss/keycloak:latest
    env_file:
      - .env
      - prod.env
    command: ["-Djboss.http.port=8100"]
    environment:
      DB_VENDOR: POSTGRES
      DB_USER: ${POSTGRES_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      DB_ADDR: micado_db
      DB_DATABASE: ${POSTGRES_DB}
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_HTTP_PORT: 8100
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8100:8100
    networks:
      - refact_net
volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      # device is the path in the host that has to be absolute
      device: $PWD/frontend
      o: bind
  postgres_data:
    driver: local
    driver_opts:
      type: none
      # device is the path in the host that has to be absolute
      device: $PWD/db_data
      o: bind
  postgres_init:
    driver: local
    driver_opts:
      type: none
      # device is the path in the host that has to be absolute
      device: $PWD/db_init
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: $PWD/backend
      o: bind
networks:
  refact_net:
    #    driver: bridge
    #external: true
